//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ADO.Net
{
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [Key]
        public int StudentID { get; set; }
        public string Name { get; set; }
    }
}
